package assets

import _ "embed"

// These byte slices expose compiled frontend assets to the dashboard server.
// Files are generated by tools/dashboard-assets/build.sh. Do not edit directly.

var (
	//go:embed htmx.min.js
	htmx2Bytes []byte

	//go:embed alpine.min.js
	alpineBytes []byte

	//go:embed app.css
	cssBytes []byte
)

// Export for use by the dashboard package.
var (
	Htmx2Bytes  = htmx2Bytes
	AlpineBytes = alpineBytes
	CSSBytes    = cssBytes
)
