// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Events() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"eventsState()\" x-init=\"start()\" class=\"space-y-8\"><div class=\"flex flex-wrap items-center justify-between gap-4 text-sm bg-[var(--panel)] border border-[var(--border)] rounded-2xl px-5 py-4 shadow-sm\"><div class=\"flex items-center gap-4\"><span class=\"inline-flex items-center gap-3 font-bold\"><span class=\"w-3 h-3 rounded-full\" x-bind:class=\"connected ? 'bg-[var(--ok)] shadow-[0_0_8px_var(--ok)]' : 'bg-[var(--err)] shadow-[0_0_8px_var(--err)]'\"></span> <span class=\"text-[var(--text)]\" x-text=\"connected ? 'Conectado à API' : 'Sem conexão'\"></span></span> <span class=\"text-[var(--muted)] border-l border-[var(--border)] pl-4 font-medium\" x-show=\"generatedAt\">atualizado <span x-text=\"generatedAgo\"></span></span></div><div class=\"flex items-center gap-3\"><button class=\"px-4 py-2 rounded-xl border border-[var(--border)] bg-[var(--bg)] text-[var(--muted)] hover:text-[var(--text)] hover:bg-[var(--panel-hover)] transition-all font-bold text-sm shadow-sm cursor-pointer\" x-on:click=\"refresh()\">↻ Atualizar</button></div></div><div class=\"grid gap-6 grid-cols-1 sm:grid-cols-2\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = StatCardAlpine("Eventos no Buffer", "fmt(events.length)", "histórico recente em memória", "text-[var(--text)]").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = StatCardAlpine("Head Atual", "fmt(events.length > 0 ? events[0].sequence : 0)", "maior sequência observada", "text-[var(--accent)]").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"font-mono text-xs space-y-2.5 max-h-[40rem] overflow-y-auto pr-3\"><template x-if=\"events.length === 0\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = EmptyState("Aguardando eventos do sistema...").Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</template><template x-for=\"e in events\" x-bind:key=\"e.sequence ?? Math.random()\"><div class=\"flex flex-col gap-1 p-3 rounded-xl bg-[var(--bg)] border border-[var(--border)] hover:border-[var(--border-focus)]/50 transition-colors shadow-sm cursor-pointer\" x-on:click=\"window.location.href='/dash/events/' + e.sequence\"><div class=\"flex gap-4 items-center\"><span class=\"text-[var(--subtle)] shrink-0 text-xs w-16 text-right font-bold\" x-text=\"'#' + (e.sequence ?? '?')\"></span> <span class=\"shrink-0 px-2 py-0.5 rounded-md text-[10px] font-bold uppercase tracking-wider\" x-bind:class=\"({\n\t\t\t\t\t\t\t\t\t\terror: 'bg-[var(--err)]/10 text-[var(--err)] border border-[var(--err)]/20',\n\t\t\t\t\t\t\t\t\t\twarning: 'bg-[var(--warn)]/10 text-[var(--warn)] border border-[var(--warn)]/20',\n\t\t\t\t\t\t\t\t\t\tinfo: 'bg-[var(--accent)]/10 text-[var(--accent)] border border-[var(--accent)]/20'\n\t\t\t\t\t\t\t\t\t})[e.kind] ?? 'bg-[var(--panel-sub)] text-[var(--muted)] border border-[var(--border)]'\" x-text=\"e.kind\"></span> <span class=\"truncate text-[var(--text)] font-semibold\" x-text=\"e.summary ?? e.kind\"></span></div><div class=\"flex gap-4\"><div class=\"w-16 shrink-0\"></div><div class=\"text-[11px] text-[var(--muted)] opacity-70 truncate\" x-show=\"e.details\" x-text=\"JSON.stringify(e.details).substring(0, 150)\"></div></div></div></template></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = card("Log de Eventos (SSE Histórico + Live)").Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><script>\n\t\t\tfunction eventsState() {\n\t\t\t\treturn {\n\t\t\t\t\tconnected: false,\n\t\t\t\t\tgeneratedAt: null,\n\t\t\t\t\tevents: [],\n\t\t\t\t\t\n\t\t\t\t\tget generatedAgo() {\n\t\t\t\t\t\tif (!this.generatedAt) return '';\n\t\t\t\t\t\tconst s = Math.max(0, (Date.now() - this.generatedAt) / 1000 | 0);\n\t\t\t\t\t\treturn s < 60 ? `${s}s atrás` : `${s/60|0}min atrás`;\n\t\t\t\t\t},\n\t\t\t\t\t\n\t\t\t\t\tfmt(n) { return n == null ? '0' : Number(n).toLocaleString('pt-BR'); },\n\t\t\t\t\t\n\t\t\t\t\tasync refresh() {\n\t\t\t\t\t\ttry {\n\t\t\t\t\t\t\tconst res = await fetch('/dash/api/events');\n\t\t\t\t\t\t\tconst data = await res.json();\n\t\t\t\t\t\t\tif(data && Array.isArray(data.events)) {\n\t\t\t\t\t\t\t\tthis.events = data.events;\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tthis.generatedAt = Date.now();\n\t\t\t\t\t\t\tthis.connected = true;\n\t\t\t\t\t\t} catch (e) {\n\t\t\t\t\t\t\tthis.connected = false;\n\t\t\t\t\t\t}\n\t\t\t\t\t},\n\t\t\t\t\t\n\t\t\t\t\tstartSSE() {\n\t\t\t\t\t\tconst es = new EventSource('/dash/api/events/stream');\n\t\t\t\t\t\tes.onmessage = (m) => {\n\t\t\t\t\t\t\ttry {\n\t\t\t\t\t\t\t\tconst d = JSON.parse(m.data);\n\t\t\t\t\t\t\t\t// Evitar duplicatas\n\t\t\t\t\t\t\t\tif(!this.events.find(x => x.sequence === d.sequence)) {\n\t\t\t\t\t\t\t\t\tthis.events.unshift(d);\n\t\t\t\t\t\t\t\t\tif(this.events.length > 500) this.events.pop();\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t} catch {}\n\t\t\t\t\t\t};\n\t\t\t\t\t},\n\t\t\t\t\t\n\t\t\t\t\tstart() {\n\t\t\t\t\t\tthis.refresh();\n\t\t\t\t\t\tthis.startSSE();\n\t\t\t\t\t}\n\t\t\t\t};\n\t\t\t}\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout("Eventos", "/dash/events", StandardNav("/dash/events")).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
