// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Frontier() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"frontierState()\" x-init=\"start()\" class=\"space-y-8\"><div class=\"flex items-center justify-between gap-4 bg-[var(--panel)] border border-[var(--border)] rounded-[20px] p-6 shadow-sm\"><div class=\"flex items-center gap-5\"><div class=\"relative flex h-3 w-3 items-center justify-center\"><span class=\"animate-ping absolute inline-flex h-full w-full rounded-full opacity-75\" x-bind:class=\"connected ? 'bg-[var(--ok)]' : 'bg-[var(--err)]'\"></span> <span class=\"relative inline-flex rounded-full h-3 w-3\" x-bind:class=\"connected ? 'bg-[var(--ok)] shadow-[0_0_8px_var(--ok)]' : 'bg-[var(--err)] shadow-[0_0_8px_var(--err)]'\"></span></div><div class=\"flex flex-col\"><span class=\"text-[15px] font-bold text-[var(--text)]\" x-text=\"connected ? 'Conectado à API' : 'Sem conexão'\"></span> <span class=\"text-[13px] text-[var(--muted)]\" x-show=\"generatedAt\">Último sync há <span x-text=\"generatedAgo\"></span></span></div></div><button class=\"px-5 py-2.5 rounded-xl border border-[var(--border)] bg-[var(--panel-sub)] text-[var(--text)] hover:bg-[var(--panel-hover)] transition-all font-semibold text-[13px] shadow-sm flex items-center gap-2 cursor-pointer\" x-on:click=\"refresh()\"><svg class=\"w-4 h-4 opacity-70\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15\"></path></svg> Atualizar</button></div><div class=\"grid gap-6 grid-cols-1 sm:grid-cols-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = StatCardAlpine("Itens na Fronteira", "fmt(frontier.length)", "tarefas sob avaliação", "text-[var(--text)]").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = StatCardAlpine("Prontos (READY)", "fmt(readyCount)", "aguardando despacho", "text-[var(--ok)]").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = StatCardAlpine("Bloqueados", "fmt(blockedCount)", "dependentes de terceiros", "text-[var(--warn)]").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"space-y-4\"><template x-if=\"frontier.length === 0\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = EmptyState("Nenhum item na fronteira de trabalho no momento.").Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</template><div class=\"space-y-4\"><template x-for=\"item in frontier\" x-bind:key=\"item.id ?? Math.random()\"><div class=\"p-6 rounded-[20px] bg-[var(--bg)] border border-[var(--border)] flex flex-col gap-4 shadow-sm hover:border-[var(--border-focus)] transition-colors group\"><div class=\"flex justify-between items-start gap-4\"><div class=\"font-bold text-[16px] text-[var(--text)] group-hover:text-white transition-colors\" x-text=\"item.title\"></div><span class=\"px-3 py-1.5 rounded-lg text-[11px] font-bold uppercase tracking-widest shadow-sm border\" x-bind:class=\"({\n\t\t\t\t\t\t\t\t\t\t\t'READY': 'bg-[var(--ok)]/10 text-[var(--ok)] border-[var(--ok)]/20',\n\t\t\t\t\t\t\t\t\t\t\t'BLOCKED': 'bg-[var(--warn)]/10 text-[var(--warn)] border-[var(--warn)]/20',\n\t\t\t\t\t\t\t\t\t\t\t'IN_PROGRESS': 'bg-[var(--info)]/10 text-[var(--info)] border-[var(--info)]/20'\n\t\t\t\t\t\t\t\t\t\t})[item.status] ?? 'bg-[var(--panel)] text-[var(--muted)] border-[var(--border)]'\" x-text=\"item.status\"></span></div><div class=\"text-[14px] text-[var(--muted)] leading-relaxed\" x-show=\"item.description\" x-text=\"item.description\"></div><div class=\"flex flex-wrap gap-2 pt-3 border-t border-[var(--border-subtle)] mt-1\" x-show=\"item.tags && item.tags.length > 0\"><template x-for=\"tag in item.tags\"><span class=\"px-2.5 py-1 bg-[var(--panel)] text-[var(--subtle)] text-[11px] rounded-md font-mono font-bold\" x-text=\"tag\"></span></template></div></div></template></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = card("Backlog Ativo").Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><script>\n\t\t\tfunction frontierState() {\n\t\t\t\treturn {\n\t\t\t\t\tconnected: false,\n\t\t\t\t\tgeneratedAt: null,\n\t\t\t\t\tfrontier: [],\n\t\t\t\t\t\n\t\t\t\t\tget generatedAgo() {\n\t\t\t\t\t\tif (!this.generatedAt) return '';\n\t\t\t\t\t\tconst s = Math.max(0, (Date.now() - this.generatedAt) / 1000 | 0);\n\t\t\t\t\t\treturn s < 60 ? `${s}s atrás` : `${s/60|0}min atrás`;\n\t\t\t\t\t},\n\t\t\t\t\t\n\t\t\t\t\tget readyCount() { return this.frontier.filter(i => i.status === 'READY').length; },\n\t\t\t\t\tget blockedCount() { return this.frontier.filter(i => i.status === 'BLOCKED').length; },\n\t\t\t\t\t\n\t\t\t\t\tfmt(n) { return n == null ? '0' : Number(n).toLocaleString('pt-BR'); },\n\t\t\t\t\t\n\t\t\t\t\tasync refresh() {\n\t\t\t\t\t\ttry {\n\t\t\t\t\t\t\tconst res = await fetch('/dash/api/frontier');\n\t\t\t\t\t\t\tconst data = await res.json();\n\t\t\t\t\t\t\tthis.frontier = data?.items || [];\n\t\t\t\t\t\t\tthis.generatedAt = Date.now();\n\t\t\t\t\t\t\tthis.connected = true;\n\t\t\t\t\t\t} catch (e) {\n\t\t\t\t\t\t\tthis.connected = false;\n\t\t\t\t\t\t}\n\t\t\t\t\t},\n\t\t\t\t\t\n\t\t\t\t\tstart() {\n\t\t\t\t\t\tthis.refresh();\n\t\t\t\t\t\tsetInterval(() => this.refresh(), 10000);\n\t\t\t\t\t}\n\t\t\t\t};\n\t\t\t}\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout("Fronteira & Backlog", "/dash/frontier", StandardNav("/dash/frontier")).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
