// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Resources() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"resourcesState()\" x-init=\"start()\" class=\"space-y-8\"><div class=\"flex items-center justify-between gap-4 bg-[var(--panel)] border border-[var(--border)] rounded-[20px] p-6 shadow-sm\"><div class=\"flex items-center gap-5\"><div class=\"relative flex h-3 w-3 items-center justify-center\"><span class=\"animate-ping absolute inline-flex h-full w-full rounded-full opacity-75\" x-bind:class=\"connected ? 'bg-[var(--ok)]' : 'bg-[var(--err)]'\"></span> <span class=\"relative inline-flex rounded-full h-3 w-3\" x-bind:class=\"connected ? 'bg-[var(--ok)] shadow-[0_0_8px_var(--ok)]' : 'bg-[var(--err)] shadow-[0_0_8px_var(--err)]'\"></span></div><div class=\"flex flex-col\"><span class=\"text-[15px] font-bold text-[var(--text)]\" x-text=\"connected ? 'Conectado à API' : 'Sem conexão'\"></span> <span class=\"text-[13px] text-[var(--muted)]\" x-show=\"generatedAt\">Último sync há <span x-text=\"generatedAgo\"></span></span></div></div><button class=\"px-5 py-2.5 rounded-xl border border-[var(--border)] bg-[var(--panel-sub)] text-[var(--text)] hover:bg-[var(--panel-hover)] transition-all font-semibold text-[13px] shadow-sm flex items-center gap-2 cursor-pointer\" x-on:click=\"refresh()\"><svg class=\"w-4 h-4 opacity-70\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15\"></path></svg> Atualizar</button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"grid gap-6 grid-cols-1 md:grid-cols-2 lg:grid-cols-3\"><template x-if=\"resources.length === 0\"><div class=\"col-span-full\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = EmptyState("Nenhuma política de quota atrelada a esse projeto.").Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></template><template x-for=\"r in resources\" x-bind:key=\"r.name ?? Math.random()\"><div class=\"p-6 rounded-[20px] bg-[var(--bg)] border border-[var(--border)] shadow-sm hover:border-[var(--border-focus)] transition-colors space-y-5\"><div class=\"flex justify-between items-center text-[14px] font-mono\"><span class=\"font-bold text-[var(--text)] truncate mr-3\" x-text=\"r.name ?? '–'\"></span> <span class=\"px-2.5 py-1 rounded-md text-[12px] font-bold tracking-wider\" x-bind:class=\"(r.usage_ratio ?? 0) > 0.8 ? 'bg-[var(--err)]/20 text-[var(--err)]' : 'bg-[var(--ok)]/10 text-[var(--ok)]'\" x-text=\"((r.usage_ratio ?? 0) * 100).toFixed(1) + '%'\"></span></div><!-- Custom Progress Bar --><div class=\"w-full bg-[var(--panel)] rounded-full h-3 overflow-hidden border border-[var(--border)]\"><div class=\"h-full rounded-full transition-all duration-1000 ease-out\" x-bind:class=\"(r.usage_ratio ?? 0) > 0.8 ? 'bg-[var(--err)]' : 'bg-white'\" x-bind:style=\"'width: ' + Math.min(100, Math.max(0, (r.usage_ratio ?? 0) * 100)) + '%'\"></div></div><div class=\"flex justify-between text-[12px] text-[var(--muted)] font-mono\"><span>Usado: <strong class=\"text-[var(--text)] font-semibold\" x-text=\"r.used ?? 0\"></strong></span> <span>Limite: <strong class=\"text-[var(--text)] font-semibold\" x-text=\"r.limit ?? 0\"></strong></span></div><div class=\"text-[11px] text-[var(--subtle)] font-mono truncate pt-3 border-t border-[var(--border)]\" x-show=\"r.reset_at\" x-text=\"'Reseta: ' + r.reset_at\"></div></div></template></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = card("Monitoramento Global de Quotas").Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><script>\n\t\t\tfunction resourcesState() {\n\t\t\t\treturn {\n\t\t\t\t\tconnected: false,\n\t\t\t\t\tgeneratedAt: null,\n\t\t\t\t\tresources: [],\n\t\t\t\t\t\n\t\t\t\t\tget generatedAgo() {\n\t\t\t\t\t\tif (!this.generatedAt) return '';\n\t\t\t\t\t\tconst s = Math.max(0, (Date.now() - this.generatedAt) / 1000 | 0);\n\t\t\t\t\t\treturn s < 60 ? `${s}s atrás` : `${s/60|0}min atrás`;\n\t\t\t\t\t},\n\t\t\t\t\t\n\t\t\t\t\tfmt(n) { return n == null ? '0' : Number(n).toLocaleString('pt-BR'); },\n\t\t\t\t\t\n\t\t\t\t\tasync refresh() {\n\t\t\t\t\t\ttry {\n\t\t\t\t\t\t\tconst res = await fetch('/dash/api/resources');\n\t\t\t\t\t\t\tconst data = await res.json();\n\t\t\t\t\t\t\tthis.resources = data?.resources || [];\n\t\t\t\t\t\t\tthis.generatedAt = Date.now();\n\t\t\t\t\t\t\tthis.connected = true;\n\t\t\t\t\t\t} catch (e) {\n\t\t\t\t\t\t\tthis.connected = false;\n\t\t\t\t\t\t}\n\t\t\t\t\t},\n\t\t\t\t\t\n\t\t\t\t\tstart() {\n\t\t\t\t\t\tthis.refresh();\n\t\t\t\t\t\tsetInterval(() => this.refresh(), 10000);\n\t\t\t\t\t}\n\t\t\t\t};\n\t\t\t}\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout("Recursos & Quotas", "/dash/resources", StandardNav("/dash/resources")).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
