// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Resources() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"resourcesState()\" x-init=\"start()\" class=\"space-y-8\"><div class=\"flex items-center gap-4 text-sm bg-[var(--panel)] border border-[var(--border)] rounded-2xl px-5 py-4 shadow-sm\"><span class=\"inline-flex items-center gap-3 font-bold\"><span class=\"w-3 h-3 rounded-full\" x-bind:class=\"connected ? 'bg-[var(--ok)] shadow-[0_0_8px_var(--ok)]' : 'bg-[var(--err)] shadow-[0_0_8px_var(--err)]'\"></span> <span class=\"text-[var(--text)]\" x-text=\"connected ? 'Conectado à API' : 'Sem conexão'\"></span></span> <span class=\"text-[var(--muted)] border-l border-[var(--border)] pl-4 font-medium\" x-show=\"generatedAt\">atualizado <span x-text=\"generatedAgo\"></span></span> <button class=\"ml-auto px-4 py-2 rounded-xl border border-[var(--border)] bg-[var(--bg)] text-[var(--muted)] hover:text-[var(--text)] hover:bg-[var(--panel-hover)] transition-all font-bold text-sm shadow-sm cursor-pointer\" x-on:click=\"refresh()\">↻ Atualizar</button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"grid gap-6 grid-cols-1 md:grid-cols-2 lg:grid-cols-3\"><template x-if=\"resources.length === 0\"><div class=\"col-span-full\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = EmptyState("Nenhum recurso de quota monitorado.").Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></template><template x-for=\"r in resources\" x-bind:key=\"r.name ?? Math.random()\"><div class=\"p-5 rounded-2xl bg-[var(--bg)] border border-[var(--border)] shadow-sm hover:border-[var(--border-focus)]/30 transition-colors space-y-4\"><div class=\"flex justify-between items-center text-sm font-mono\"><span class=\"font-bold text-[var(--text)] truncate mr-2\" x-text=\"r.name ?? '–'\"></span> <span class=\"px-2 py-1 rounded-md text-xs font-bold tracking-widest\" x-bind:class=\"(r.usage_ratio ?? 0) > 0.8 ? 'bg-[var(--err)]/20 text-[var(--err)]' : 'bg-[var(--ok)]/20 text-[var(--ok)]'\" x-text=\"((r.usage_ratio ?? 0) * 100).toFixed(1) + '%'\"></span></div><div class=\"w-full bg-[var(--panel)] rounded-full h-2.5 overflow-hidden border border-[var(--border)]\"><div class=\"h-full rounded-full transition-all duration-500 ease-out\" x-bind:class=\"(r.usage_ratio ?? 0) > 0.8 ? 'bg-[var(--err)] shadow-[0_0_8px_var(--err)]' : 'bg-[var(--ok)] shadow-[0_0_8px_var(--ok)]'\" x-bind:style=\"'width: ' + Math.min(100, Math.max(0, (r.usage_ratio ?? 0) * 100)) + '%'\"></div></div><div class=\"flex justify-between text-xs text-[var(--muted)] font-mono font-medium\"><span>Usado: <strong class=\"text-[var(--text)]\" x-text=\"r.used ?? 0\"></strong></span> <span>Limite: <strong class=\"text-[var(--text)]\" x-text=\"r.limit ?? 0\"></strong></span></div><div class=\"text-[10px] text-[var(--subtle)] font-mono truncate\" x-show=\"r.reset_at\" x-text=\"'Reseta: ' + r.reset_at\"></div></div></template></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = card("Estado Global de Quotas").Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><script>\n\t\t\tfunction resourcesState() {\n\t\t\t\treturn {\n\t\t\t\t\tconnected: false,\n\t\t\t\t\tgeneratedAt: null,\n\t\t\t\t\tresources: [],\n\t\t\t\t\t\n\t\t\t\t\tget generatedAgo() {\n\t\t\t\t\t\tif (!this.generatedAt) return '';\n\t\t\t\t\t\tconst s = Math.max(0, (Date.now() - this.generatedAt) / 1000 | 0);\n\t\t\t\t\t\treturn s < 60 ? `${s}s atrás` : `${s/60|0}min atrás`;\n\t\t\t\t\t},\n\t\t\t\t\t\n\t\t\t\t\tfmt(n) { return n == null ? '0' : Number(n).toLocaleString('pt-BR'); },\n\t\t\t\t\t\n\t\t\t\t\tasync refresh() {\n\t\t\t\t\t\ttry {\n\t\t\t\t\t\t\tconst res = await fetch('/dash/api/resources');\n\t\t\t\t\t\t\tconst data = await res.json();\n\t\t\t\t\t\t\tthis.resources = data?.resources || [];\n\t\t\t\t\t\t\tthis.generatedAt = Date.now();\n\t\t\t\t\t\t\tthis.connected = true;\n\t\t\t\t\t\t} catch (e) {\n\t\t\t\t\t\t\tthis.connected = false;\n\t\t\t\t\t\t}\n\t\t\t\t\t},\n\t\t\t\t\t\n\t\t\t\t\tstart() {\n\t\t\t\t\t\tthis.refresh();\n\t\t\t\t\t\tsetInterval(() => this.refresh(), 10000);\n\t\t\t\t\t}\n\t\t\t\t};\n\t\t\t}\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout("Recursos & Quotas", "/dash/resources", StandardNav("/dash/resources")).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
